name: generate animation

on: 
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch: 

  push:
   branches:
     - main

jobs:
  generate:
    permissions: 
      contents: write

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: generate github-contri-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Priyanshu1-62
          outputs: |
            dist/github-contri-grid-snake.svg
            dist/github-contri-grid-snake-dark.svg?palette=github-dark

      - name: push the generated svg to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: output
          publish_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}


